name: "Label Sync"
description: "Create or update labels from labels.yml"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: sudo apt-get install -y jq yq
      shell: bash

    - name: Apply labels
      run: |
        for row in $(yq -c '.[]' $GITHUB_ACTION_PATH/labels.yml); do
          name=$(echo $row | jq -r '.name')
          color=$(echo $row | jq -r '.color')
          description=$(echo $row | jq -r '.description')

          echo "Syncing label: $name"
          gh label create "$name" --color "$color" --description "$description" || \
          gh label edit "$name" --color "$color" --description "$description"
        done
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
