name: bump-version
description: "High-performance smart version bumper"
author: "recursivezero"

inputs:
  node-version:
    description: "Node.js version"
    default: "18"
  enable-bump:
    description: "whether bump is enabled"
    default: "true"
  enable-changelog:
    description: "whether changelog to write or not"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Environment Detection
      id: env
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          echo "is_node=true" >> $GITHUB_OUTPUT
        else
          echo "is_node=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Node.js Runtime
      if: steps.env.outputs.is_node == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Execute Versioning Suite
      if: steps.env.outputs.is_node == 'true'
      shell: bash
      env:
        INPUT_ENABLE_BUMP: ${{ inputs.enable-bump }}
        INPUT_ENABLE_CHANGELOG: ${{ inputs.enable-changelog }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # 1. Identity Config
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # 2. Permissions
        chmod +x $ACTION_PATH/bump.sh $ACTION_PATH/changelog.sh

        # 3. Pre-bump commit
        git add -A
        git commit -m "chore: prepare for version bump" || true

        # 4. Bump Execution
        if [ "$INPUT_ENABLE_BUMP" = "true" ]; then
          $ACTION_PATH/bump.sh
          echo "### Bump Result: ✅ Success" >> $GITHUB_STEP_SUMMARY
        fi

        # 5. Changelog Execution
        if [ "$INPUT_ENABLE_CHANGELOG" = "true" ]; then
          $ACTION_PATH/changelog.sh
          git add CHANGELOG.md || true
          git commit -m "chore: update changelog" || true
        fi

        # 6. Final Sync
        git push --follow-tags
