name: "Auto Format Issue Title"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  format_title:
    runs-on: ubuntu-latest
    steps:
      - name: Format issue title
        uses: recursivezero/action-club/.github/actions/format-issue-title@main
        with:
          prefix: RAC # change this as per your convention
          dry_run: false
